apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshop-dotnet
  namespace: openshift-gitops
spec:
  destination:
    namespace: eshop-dotnet
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: https://github.com/kevchu3/eShop-dotnet-tekton-pipeline.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
